# Generated by Django 4.2.4 on 2023-08-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_service_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='tittle',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
