# Generated by Django 4.2.4 on 2023-08-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_name_service_tittle_alter_service_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='tittle',
            new_name='title',
        ),
    ]
