# Generated by Django 4.2.4 on 2023-08-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_tittle_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
